# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c02b24db4e5467cd35d589db58f1d794763dee0d0272a46d85c6103c0c0560c10a5f248d0be7d4d68a7ed8f74036ae5ff7d3c66d8c86b65368c08f2e59f737

test:
  secret_key_base: 73ed2979a07394a81ba059c4a2a703b1e7510831da235f0b28eef2221cc1936bb5d4c84d19b732ead5713a6a6ddf2edbcf6ac9469d077bf40eff599d6cf561f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
